SELECT * FROM stock_prices ORDER BY recorded_at DESC;
SELECT * FROM stocks;
SELECT * FROM risk_scores;

ALTER TABLE stock_prices ADD COLUMN uid CHAR(36) NOT NULL UNIQUE AFTER id;
ALTER TABLE daily_summary ADD COLUMN uid CHAR(36) NOT NULL UNIQUE AFTER id;
ALTER TABLE company_fundamentals ADD COLUMN uid CHAR(36) NOT NULL UNIQUE AFTER id;
ALTER TABLE risk_scores ADD COLUMN uid CHAR(36) NOT NULL UNIQUE AFTER id;
ALTER TABLE news_cache ADD COLUMN uid CHAR(36) NOT NULL UNIQUE AFTER id;
