# Generated by Django 5.1.4 on 2024-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('numero_pokedex', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
            ],
            options={
                'db_table': 'pokemon',
            },
        ),
    ]
