FROM python:3.10-slim

WORKDIR /app
COPY . .
COPY project/backend/fastapi/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

# No COPY de código. Se monta por volumen.
