db.intents.insertMany([
    { "frase": "trae las estadísticas de", "intencion": "info" },
    { "frase": "quitar a", "intencion": "delete" },
    { "frase": "agregar a mi equipo", "intencion": "add" },
    { "frase": "quién ganaría entre", "intencion": "compare" },
    { "frase": "Dame los datos de", "intencion":"info" },
    { "frase": "Ver los datos de", "intencion":"info" },
    { "frase": "Muéstrame los datos de", "intencion":"info" },
    { "frase": "¿Qué información tienes de?", "intencion":"info" },
    { "frase": "Quiero saber más de", "intencion":"info" },
    { "frase": "Detalles sobre", "intencion":"info" },
    { "frase": "Estadísticas de", "intencion":"info" },
    { "frase": "Dame detalles de", "intencion":"info" },
    { "frase": "Dame información de", "intencion":"info" },
    { "frase": "¿Qué puedes decirme de?", "intencion":"info" },
    { "frase": "Necesito información de", "intencion":"info" },
    { "frase": "Mostrar los datos de", "intencion":"info" },
    { "frase": "Ver estadísticas de", "intencion":"info" },
    { "frase": "Características de", "intencion":"info" },
    { "frase": "Quiero ver los detalles de", "intencion":"info" },
    { "frase": "Dame las características de", "intencion":"info" },
    { "frase": "Datos sobre", "intencion":"info" },
    { "frase": "Muéstrame las estadísticas de", "intencion":"info" },
    { "frase": "¿Qué detalles tienes sobre?", "intencion":"info" },
    { "frase": "Información completa de", "intencion":"info" },
    { "frase": "Ver detalles sobre", "intencion":"info" },
    { "frase": "Estadísticas completas de", "intencion":"info" },
    { "frase": "¿Qué sabes de?", "intencion":"info" },
    { "frase": "Muéstrame información de", "intencion":"info" },
    { "frase": "Detalles completos de", "intencion":"info" },
    { "frase": "Ver todo sobre", "intencion":"info" },
    { "frase": "Dame una descripción de", "intencion":"info" },
    { "frase": "Información adicional de", "intencion":"info" },
    { "frase": "Quiero consultar sobre", "intencion":"info" },
    { "frase": "Dame más datos de", "intencion":"info" },
    { "frase": "Detalles adicionales de", "intencion":"info" },
    { "frase": "Quiero conocer más de", "intencion":"info" },
    { "frase": "Dame todos los datos de", "intencion":"info" },
    { "frase": "Muéstrame más información sobre", "intencion":"info" },
    { "frase": "Dame un resumen de", "intencion":"info" },
    { "frase": "Datos detallados de", "intencion":"info" },
    { "frase": "Ver datos completos de", "intencion":"info" },
    { "frase": "Más información de", "intencion":"info" },
    { "frase": "¿Qué características tiene?", "intencion":"info" },
    { "frase": "Consultar detalles de", "intencion":"info" },
    { "frase": "Mostrar más datos sobre", "intencion":"info" },
    { "frase": "Información básica de", "intencion":"info" },
    { "frase": "Datos esenciales de", "intencion":"info" },
    { "frase": "Dame el historial de", "intencion":"info" },
    { "frase": "Ver historial de", "intencion":"info" },
    { "frase": "Consultar datos sobre", "intencion":"info" },
    { "frase": "¿Tienes información de?", "intencion":"info" },
    { "frase": "Información necesaria de", "intencion":"info" },
    { "frase": "Dame referencias sobre", "intencion":"info" },
    { "frase": "Muéstrame todo sobre", "intencion":"info" },
    {"frase": "Dame los datos de", "intencion": "compare"},
    {"frase": "Ver los datos de", "intencion": "compare"},
    {"frase": "Muéstrame los datos de", "intencion": "compare"},
    {"frase": "¿Qué información tienes de?", "intencion": "compare"},
    {"frase": "Quiero saber más de", "intencion": "compare"},
    {"frase": "Detalles sobre", "intencion": "compare"},
    {"frase": "Estadísticas de", "intencion": "compare"},
    {"frase": "Dame detalles de", "intencion": "compare"},
    {"frase": "Dame información de", "intencion": "compare"},
    {"frase": "¿Qué puedes decirme de?", "intencion": "compare"},
    {"frase": "Necesito información de", "intencion": "compare"},
    {"frase": "Mostrar los datos de", "intencion": "compare"},
    {"frase": "Ver estadísticas de", "intencion": "compare"},
    {"frase": "Características de", "intencion": "compare"},
    {"frase": "Quiero ver los detalles de", "intencion": "compare"},
    {"frase": "Dame las características de", "intencion": "compare"},
    {"frase": "Datos sobre", "intencion": "compare"},
    {"frase": "Muéstrame las estadísticas de", "intencion": "compare"},
    {"frase": "¿Qué detalles tienes sobre?", "intencion": "compare"},
    {"frase": "Información completa de", "intencion": "compare"},
    {"frase": "Ver detalles sobre", "intencion": "compare"},
    {"frase": "Estadísticas completas de", "intencion": "compare"},
    {"frase": "¿Qué sabes de?", "intencion": "compare"},
    {"frase": "Muéstrame información de", "intencion": "compare"},
    {"frase": "Detalles completos de", "intencion": "compare"},
    {"frase": "Ver todo sobre", "intencion": "compare"},
    {"frase": "Dame una descripción de", "intencion": "compare"},
    {"frase": "Información adicional de", "intencion": "compare"},
    {"frase": "Quiero consultar sobre", "intencion": "compare"},
    {"frase": "Dame más datos de", "intencion": "compare"},
    {"frase": "Detalles adicionales de", "intencion": "compare"},
    {"frase": "Quiero conocer más de", "intencion": "compare"},
    {"frase": "Dame todos los datos de", "intencion": "compare"},
    {"frase": "Muéstrame más información sobre", "intencion": "compare"},
    {"frase": "Dame un resumen de", "intencion": "compare"},
    {"frase": "Datos detallados de", "intencion": "compare"},
    {"frase": "Ver datos completos de", "intencion": "compare"},
    {"frase": "Más información de", "intencion": "compare"},
    {"frase": "¿Qué características tiene?", "intencion": "compare"},
    {"frase": "Consultar detalles de", "intencion": "compare"},
    {"frase": "Mostrar más datos sobre", "intencion": "compare"},
    {"frase": "Información básica de", "intencion": "compare"},
    {"frase": "Datos esenciales de", "intencion": "compare"},
    {"frase": "Dame el historial de", "intencion": "compare"},
    {"frase": "Ver historial de", "intencion": "compare"},
    {"frase": "Consultar datos sobre", "intencion": "compare"},
    {"frase": "¿Tienes información de?", "intencion": "compare"},
    {"frase": "Información necesaria de", "intencion": "compare"},
    {"frase": "Dame referencias sobre", "intencion": "compare"},
    {"frase": "Muéstrame todo sobre", "intencion": "compare"},
    { "frase": "Eliminar a", "intencion":"delete" },
    { "frase": "Borrar a", "intencion":"delete" },
    { "frase": "Quitar a", "intencion":"delete" },
    { "frase": "Sácalo de", "intencion":"delete" },
    { "frase": "Elimínalo de", "intencion":"delete" },
    { "frase": "Quitar del equipo", "intencion":"delete" },
    { "frase": "Borrar del equipo", "intencion":"delete" },
    { "frase": "Sácalo del grupo", "intencion":"delete" },
    { "frase": "Quita ese dato", "intencion":"delete" },
    { "frase": "Borra ese registro", "intencion":"delete" },
    { "frase": "Eliminar ese dato", "intencion":"delete" },
    { "frase": "Elimina de la lista", "intencion":"delete" },
    { "frase": "Elimina del registro", "intencion":"delete" },
    { "frase": "Elimina de la base de datos", "intencion":"delete" },
    { "frase": "Elimina por completo", "intencion":"delete" },
    { "frase": "Quita esta entrada", "intencion":"delete" },
    { "frase": "Borra este dato", "intencion":"delete" },
    { "frase": "Sácalo del sistema", "intencion":"delete" },
    { "frase": "Borra este elemento", "intencion":"delete" },
    { "frase": "Quitar del sistema", "intencion":"delete" },
    { "frase": "Eliminar permanentemente", "intencion":"delete" },
    { "frase": "Borra este registro", "intencion":"delete" },
    { "frase": "Sácalo definitivamente", "intencion":"delete" },
    { "frase": "Quitar de la lista", "intencion":"delete" },
    { "frase": "Borra esta información", "intencion":"delete" },
    { "frase": "Elimina esta entrada", "intencion":"delete" },
    { "frase": "Quitar del equipo", "intencion":"delete" },
    { "frase": "Sácalo de aquí", "intencion":"delete" },
    { "frase": "Borra la información de", "intencion":"delete" },
    { "frase": "Elimina todos los datos de", "intencion":"delete" },
    { "frase": "Borrar por completo", "intencion":"delete" },
    { "frase": "Quitar del historial", "intencion":"delete" },
    { "frase": "Eliminar completamente", "intencion":"delete" },
    { "frase": "Sácalo para siempre", "intencion":"delete" },
    { "frase": "Quitar de esta base", "intencion":"delete" },
    { "frase": "Borra esta referencia", "intencion":"delete" },
    { "frase": "Eliminar información", "intencion":"delete" },
    { "frase": "Sácalo del historial", "intencion":"delete" },
    { "frase": "Quitar esta entrada", "intencion":"delete" },
    { "frase": "Borra este registro", "intencion":"delete" },
    { "frase": "Elimina los datos de", "intencion":"delete" },
    { "frase": "Sácalo de la lista", "intencion":"delete" },
    { "frase": "Borra este ítem", "intencion":"delete" },
    { "frase": "Elimina este usuario", "intencion":"delete" },
    { "frase": "Quita este campo", "intencion":"delete" },
    { "frase": "Borra todo de", "intencion":"delete" },
    { "frase": "Elimina esta sección", "intencion":"delete" },
    { "frase": "Sácalo de este grupo", "intencion":"delete" },
    { "frase": "Borra esta categoría", "intencion":"delete" },
    { "frase": "Elimina esta información", "intencion":"delete" },
    { "frase": "Agregar a mi equipo","intencion":"add" },
    { "frase": "Añadir al equipo","intencion":"add" },
    { "frase": "Incluye a","intencion":"add" },
    { "frase": "Ponlo en mi equipo","intencion":"add" },
    { "frase": "Ponlo en la lista","intencion":"add" },
    { "frase": "Agrégalo al grupo","intencion":"add" },
    { "frase": "Añádelo al equipo","intencion":"add" },
    { "frase": "Añádelo al registro","intencion":"add" },
    { "frase": "Añadir a la lista","intencion":"add" },
    { "frase": "Ponlo en el sistema","intencion":"add" },
    { "frase": "Inclúyelo en mi equipo","intencion":"add" },
    { "frase": "Agrega este dato","intencion":"add" },
    { "frase": "Incluye esta entrada","intencion":"add" },
    { "frase": "Añádelo al historial","intencion":"add" },
    { "frase": "Registra este dato","intencion":"add" },
    { "frase": "Inclúyelo en la base","intencion":"add" },
    { "frase": "Agrégalo al registro","intencion":"add" },
    { "frase": "Agrega esta información","intencion":"add" },
    { "frase": "Añadir este elemento","intencion":"add" },
    { "frase": "Añade al historial","intencion":"add" },
    { "frase": "Agrégalo a la base","intencion":"add" },
    { "frase": "Ponlo en esta lista","intencion":"add" },
    { "frase": "Registra a","intencion":"add" },
    { "frase": "Incluye a este elemento","intencion":"add" },
    { "frase": "Agrega este usuario","intencion":"add" },
    { "frase": "Añádelo al sistema","intencion":"add" },
    { "frase": "Añade este campo","intencion":"add" },
    { "frase": "Ponlo en la categoría","intencion":"add" },
    { "frase": "Añade esta entrada","intencion":"add" },
    { "frase": "Agrégalo a este grupo","intencion":"add" },
    { "frase": "Inclúyelo aquí","intencion":"add" },
    { "frase": "Registra este ítem","intencion":"add" },
    { "frase": "Agrégalo a este equipo","intencion":"add" },
    { "frase": "Ponlo en esta sección","intencion":"add" },
    { "frase": "Registra este campo","intencion":"add" },
    { "frase": "Añádelo al conjunto","intencion":"add" },
    { "frase": "Agrégalo definitivamente","intencion":"add" },
    { "frase": "Inclúyelo completamente","intencion":"add" },
    { "frase": "Añade este registro","intencion":"add" },
    { "frase": "Incluye este ítem","intencion":"add" },
    { "frase": "Agrega este campo","intencion":"add" },
    { "frase": "Añade este usuario","intencion":"add" },
    { "frase": "Ponlo en este grupo","intencion":"add" },
    { "frase": "Registra esta entrada","intencion":"add" },
    { "frase": "Incluye este dato","intencion":"add" },
    { "frase": "Añádelo al registro","intencion":"add" },
    { "frase": "Agrégalo al historial","intencion":"add" },
    { "frase": "Ponlo aquí","intencion":"add" },
    { "frase": "Incluye esta categoría","intencion":"add" },
    { "frase": "Registra esta información","intencion":"add" }
])
