#version: '3'
#
#services:
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
###< doctrine/doctrine-bundle ###

services:
###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - "27017"
###< doctrine/mongodb-odm-bundle ###
